/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Canvas: typeof import('./src/components/Canvas.vue')['default']
    ILucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
    ILucideCircle: typeof import('~icons/lucide/circle')['default']
    ILucideHand: typeof import('~icons/lucide/hand')['default']
    ILucideImage: typeof import('~icons/lucide/image')['default']
    ILucideMinus: typeof import('~icons/lucide/minus')['default']
    ILucideMousePointer2: typeof import('~icons/lucide/mouse-pointer2')['default']
    ILucidePenTool: typeof import('~icons/lucide/pen-tool')['default']
    ILucideSquare: typeof import('~icons/lucide/square')['default']
    ILucideType: typeof import('~icons/lucide/type')['default']
    ILucideZoomIn: typeof import('~icons/lucide/zoom-in')['default']
    ILucideZoomOut: typeof import('~icons/lucide/zoom-out')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
    ToolSelector: typeof import('./src/components/ToolSelector.vue')['default']
    ZoomControls: typeof import('./src/components/ZoomControls.vue')['default']
  }
}
