/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'IHeroicons:handRaisedSolid': typeof import('~icons/heroicons/hand-raised-solid')['default']
    'ILucide:circle': typeof import('~icons/lucide/circle')['default']
    'ILucide:edit': typeof import('~icons/lucide/edit')['default']
    'IMaterialSymbols:squareOutline': typeof import('~icons/material-symbols/square-outline')['default']
    'IMdi:counter': typeof import('~icons/mdi/counter')['default']
    NButton: typeof import('naive-ui')['NButton']
  }
}
